config/routes.rb
Rails.application.routes.draw do
  resources :toys
  get 'welcome/index'

  get 'welcome/goodbye'

  root 'welcome#index'

end

app/models/toy.rb
class Toy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: [:show, :edit, :update, :destroy]

  # GET /toys
  # GET /toys.json
  def index
    @toys = Toy.all
  end

  # GET /toys/1
  # GET /toys/1.json
  def show
  end

  # GET /toys/new
  def new
    @toy = Toy.new
  end

  # GET /toys/1/edit
  def edit
  end

  # POST /toys
  # POST /toys.json
  def create
    @toy = Toy.new(toy_params)

    respond_to do |format|
      if @toy.save
        format.html { redirect_to @toy, notice: 'Toy was successfully created.' }
        format.json { render :show, status: :created, location: @toy }
      else
        format.html { render :new }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toys/1
  # PATCH/PUT /toys/1.json
  def update
    respond_to do |format|
      if @toy.update(toy_params)
        format.html { redirect_to @toy, notice: 'Toy was successfully updated.' }
        format.json { render :show, status: :ok, location: @toy }
      else
        format.html { render :edit }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1
  # DELETE /toys/1.json
  def destroy
    @toy.destroy
    respond_to do |format|
      format.html { redirect_to toys_url, notice: 'Toy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toy
      @toy = Toy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toy_params
      params.require(:toy).permit(:name, :descrition, :manufactuer, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @current_time = Time.now
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoreDemos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/toys/_form.html.erb
<%= form_for(@toy) do |f| %>
  <% if @toy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@toy.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
      <% @toy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descrition %><br>
    <%= f.text_area :descrition %>
  </div>
  <div class="field">
    <%= f.label :manufactuer %><br>
    <%= f.text_field :manufactuer %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/toys/edit.html.erb
<h1>Editing Toy</h1>

<%= render 'form' %>

<%= link_to 'Show', @toy %> |
<%= link_to 'Back', toys_path %>

app/views/toys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Toys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descrition</th>
      <th>Manufactuer</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toys.each do |toy| %>
      <tr>
        <td><%= toy.name %></td>
        <td><%= toy.descrition %></td>
        <td><%= toy.manufactuer %></td>
        <td><%= toy.price %></td>
        <td><%= link_to 'Show', toy %></td>
        <td><%= link_to 'Edit', edit_toy_path(toy) %></td>
        <td><%= link_to 'Destroy', toy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Toy', new_toy_path %>

app/views/toys/new.html.erb
<h1>New Toy</h1>

<%= render 'form' %>

<%= link_to 'Back', toys_path %>

app/views/toys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @toy.name %>
</p>

<p>
  <strong>Descrition:</strong>
  <%= @toy.descrition %>
</p>

<p>
  <strong>Manufactuer:</strong>
  <%= @toy.manufactuer %>
</p>

<p>
  <strong>Price:</strong>
  <%= @toy.price %>
</p>

<%= link_to 'Edit', edit_toy_path(@toy) %> |
<%= link_to 'Back', toys_path %>

app/views/welcome/goodbye.html.erb
<h1>Welcome#goodbye</h1>
<p>Find me in app/views/welcome/goodbye.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Hello world at time: <%= Time.now %></p>
Hello <%= link_to "Goodbye", welcome_goodbye_path %>!